django/mysite/myprofile/urls.py
from django.urls import path

from myprofile import views

app_name = 'myprofile'

urlpatterns = [
    path('edit/', views.edit, name='edit'),
    path('', views.profile, name='detail'),
    path('user', views.UserList.as_view()),
    path('user/<int:pk>', views.UserDetail.as_view())
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from mysite import settings

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="API M431",
      default_version='v1'
   ),
   public=False,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # path('api/', include('api.urls')),

    path('accounts/', include('allauth.urls')),

    path('profile/', include('myprofile.urls')),

    path('', include('main.urls')),  # homepage

    path('crud/', include('crud.urls')),  # homepage

    path('admin1337/', admin.site.urls),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'), 

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns \
                  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #serve media files in development

django/mysite/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

django/mysite/myprofile/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)  # La liaison OneToOne vers le modele User

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

django/mysite/myprofile/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from myprofile.models import UserProfile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [] #['exemple',]

django/mysite/myprofile/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect
from rest_framework import serializers

from myprofile.models import UserProfile
from myprofile.forms import UserProfileEditForm, UserEditForm

from common.drf import CustomRetrieveUpdateDestroyAPIView, CustomListAPIView, CustomPermission
from django_filters.rest_framework import DjangoFilterBackend


class UserSerializer(serializers.ModelSerializer):

    class Meta:
        model = User
        fields = ('id', 'first_name', 'last_name', 'username', 'email') 
        read_only_fields = ('id',)

def profile(request):
    return render(request, 'myprofile/detail.html')


def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        user_profile_form = UserProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()
            return redirect("myprofile:detail")
    else:
        user_form = UserEditForm(instance=request.user)
        user_profile_form = UserProfileEditForm(instance=request.user.profile)

    return render(request,
                  'myprofile/edit.html',
                  {'user_form': user_form,
                   'user_profile_form': user_profile_form})


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        userprofile = UserProfile(user=user)
        userprofile.save()


class UserList(CustomListAPIView):
    """
    List all instances.
    """
    model = User
    exclude = ('password',)
    filter_fields = ('username',)
    search_fields = ('username',)
    # permission_classes = [CustomPermission]


class UserDetail(CustomRetrieveUpdateDestroyAPIView):
    """
    Show / Update / Delete one instance.
    """
    model = User
    exclude = ('password',)
    # permission_classes = [CustomPermission]

def jwt_response_payload_handler(token, user=None, request=None):
    """ Custom response payload handler.

    This function controlls the custom payload after login or token refresh. This data is returned through the web API.
    """
    serializedprofile = UserSerializer(user)
    return {
        'token': token,
        'user': serializedprofile.data
    }
    


# Exemple
# class UserList(CustomListCreateAPIView):
#     """
#     List all instances, or create a new one.
#     """
#     model = User
#     fields = None
#     depth = 2
#     exclude = ('password',) 
#     filter_fields = ('username',)
#     search_fields = ('username',)
#     permission_classes = [CustomPermission]

django/mysite/myprofile/templates/myprofile/base.html
{% extends "base.html" %}
{% load i18n static %}

{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block extra_head %}
<link rel='stylesheet' type='text/css' href="{% static 'myprofile/style.css' %}" />
{% endblock %}

{% block content %}
{% endblock %}

django/mysite/myprofile/templates/myprofile/detail.html
{% extends "myprofile/base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-lg-6 border mt-5 p-5">
            <h2>{% trans "My account" %}</h2>
            <div class="table-responsive">
                <table class="table tableprofile">
                    <tr>
                        <td>{% trans "First name" %}:</td><td>{{request.user.first_name}}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Last name" %}:</td><td>{{request.user.last_name}}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Email" %}:</td><td>{{request.user.email}}</td>
                    </tr>
                </table>
            </div>

            <a href="{% url 'myprofile:edit' %}" class="btn btn-info">{% trans "Edit" %}</a>

        </div>
    </div>
</div>
{% endblock %}

django/mysite/myprofile/templates/myprofile/edit.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-lg-6 border mt-5 p-5">
            <h2>{% trans "Modifier mon compte" %}</h2>

            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {% bootstrap_form user_form %}
                {% bootstrap_form user_profile_form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">{% trans 'Valider' %}</button>
                {% endbuttons %}
            </form>
        </div> <!-- .col -->
    </div> <!-- .row -->
</div>
{% endblock %}