django/mysite/myprofile/urls.py
from django.urls import path

from myprofile import views

app_name = 'myprofile'

urlpatterns = [
    path('edit/', views.edit, name='edit'),
    path('', views.profile, name='detail'),
    path('user', views.UserList.as_view()),
    path('user/<int:pk>', views.UserDetail.as_view())
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from mysite import settings

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="API M431",
      default_version='v1'
   ),
   public=False,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # path('api/', include('api.urls')),

    path('accounts/', include('allauth.urls')),

    path('profile/', include('myprofile.urls')),

    path('', include('main.urls')),  # homepage

    path('crud/', include('crud.urls')),  # homepage

    path('admin1337/', admin.site.urls),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'), 

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns \
                  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #serve media files in development

django/mysite/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

django/mysite/templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel='stylesheet' type='text/css' href="{% static 'css/style.css' %}" />

    <title>{{request.META.HTTP_HOST}} - A REMPLACER</title>
  
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Myproject</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav w-100">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown ml-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% trans "Menu" %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'myprofile:detail' %}">{% trans "My Account" %}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              {% else %}
                <a class="dropdown-item" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                <a class="dropdown-item" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <script src="{% static 'lib/vue/vue.js' %}"></script>

    {% block extra_body %}{% endblock %}
  </body>
</html>