django/mysite/crud/urls.py
from django.urls import path

from crud import views

app_name = 'crud'

urlpatterns = [
    path('', views.object_list, name='object_list'),
    path('new', views.object_create, name='object_new'),
    path('edit/<int:pk>', views.object_update, name='object_edit'),
    path('delete/<int:pk>', views.object_delete, name='object_delete'),
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from mysite import settings

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="API M431",
      default_version='v1'
   ),
   public=False,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # path('api/', include('api.urls')),

    path('accounts/', include('allauth.urls')),

    path('profile/', include('myprofile.urls')),

    path('', include('main.urls')),  # homepage

    path('crud/', include('crud.urls')),  # homepage

    path('admin1337/', admin.site.urls),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'), 

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns \
                  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #serve media files in development

django/mysite/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

django/mysite/crud/models.py
from django.db import models
from django.urls import reverse

class MyObject(models.Model):
    title = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('crud:object_edit', kwargs={'pk': self.pk})

django/mysite/crud/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm, Form
from django.contrib import messages

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from crud.models import MyObject
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, HTML


class MyObjectForm(ModelForm):

    class Meta:
        model = MyObject
        fields = '__all__'


# class MyObjectForm(ModelForm):
#     class Meta:
#         model = MyObject
#         fields = ['title',]


# @login_required
def object_list(request):

    object_list = MyObject.objects.all() #.order_by('-created_at')
    context = {
        'page_title': 'Objects list',
        'object_list': object_list
    }

    return render(request, 'crud/object_list.html', context)

# @login_required
def object_create(request):

    if request.method == 'POST':
        form = MyObjectForm(request.POST, files=request.FILES)
        if form.is_valid():
            object = form.save(commit=False)
            # object.user = request.user.profile
            object.save()
            messages.add_message(request, messages.INFO, 'You created succesfully your object.')
            return redirect('crud:object_list')
    else:
        form = MyObjectForm()

    context = {
        'page_title': 'Create a new object',
        'form': form,
    }
    return render(request, 'crud/object_form.html', context)

# @login_required
def object_update(request, pk):

    object = get_object_or_404(MyObject, pk=pk)
    # object = get_object_or_404(MyObject, pk=pk, creator=request.user.profile)

    if request.method == 'POST':
        form = MyObjectForm(request.POST, files=request.FILES, instance=object)

        if form.is_valid():
            object_update = form.save(commit=False)
            # object.user = request.user.profile
            object_update.save()
            messages.add_message(request, messages.INFO, 'You updated succesfully your object.')
            return redirect('crud:object_list')

    else:
        form = MyObjectForm(request.POST or None, instance=object)
    
    context = {
        'page_title': 'Edit an object',
        'form': form,
        'object': object,
    }
    return render(request, 'crud/object_form.html', context)

# @login_required
def object_delete(request, pk):

    object = get_object_or_404(MyObject, pk=pk)
    # object = get_object_or_404(MyObject, pk=pk, creator=request.user.profile)
    if request.method=='POST':
        object.delete()
        messages.add_message(request, messages.INFO, 'You deleted succesfully your object.')
        return redirect('crud:object_list')

    context = {
        'page_title': 'Delete a object',
        'object':object,
    }
    return render(request, 'crud/object_confirm_delete.html', context)

django/mysite/crud/templates/crud/base.html
{% extends "base.html" %}
{% load i18n static %}

{% block head_title %}{% trans "CRUD" %}{% endblock %}

{% block extra_head %}
<link rel='stylesheet' type='text/css' href="{% static 'crud/style.css' %}" />
{% endblock %}

{% block content %}
{% endblock %}

django/mysite/crud/templates/crud/object_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-4 offset-md-4">
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

django/mysite/crud/templates/crud/object_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h3>My objects</h3>

            <div class="mt-4">
        
                <table class="table table-bordered">
                    
                    {% for object in object_list %}
        
                    <tr>
                        <td>{{ object.title }}</td>
                        <td>
                            <a href="{{ object.get_absolute_url }}" class="btn btn-info btn-sm">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg>
                            </a>
                            <a href="{% url 'crud:object_delete' object.id %}" class="btn btn-danger btn-sm">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash2-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M2.037 3.225l1.684 10.104A2 2 0 0 0 5.694 15h4.612a2 2 0 0 0 1.973-1.671l1.684-10.104C13.627 4.224 11.085 5 8 5c-3.086 0-5.627-.776-5.963-1.775z"/>
                                    <path fill-rule="evenodd" d="M12.9 3c-.18-.14-.497-.307-.974-.466C10.967 2.214 9.58 2 8 2s-2.968.215-3.926.534c-.477.16-.795.327-.975.466.18.14.498.307.975.466C5.032 3.786 6.42 4 8 4s2.967-.215 3.926-.534c.477-.16.795-.327.975-.466zM8 5c3.314 0 6-.895 6-2s-2.686-2-6-2-6 .895-6 2 2.686 2 6 2z"/>
                                </svg>
                            </a>
                        </td>
        
                        {% empty %}
                            <td><strong>You have no objects for the moment</strong></td>
                        {% endfor %}
                    </tr>
        
                </table>
            </div>
        
            <a href="{% url 'crud:object_new' %}" class="btn btn-info">Add a new object</a>
        </div>
    </div>
</div>
{% endblock %}